import { Photo } from './types';

export const photos: Photo[] = [
  {
    id: '1',
    title: 'Misty Yosemite Valley',
    category: 'Landscape',
    imageUrl: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1600&auto=format&fit=crop&q=85',
    location: 'Yosemite National Park, USA',
    date: 'Oct 12, 2025',
    camera: 'Hasselblad X2D 100C',
    lens: 'XCD 38mm f/2.5',
    shutter: '1/250s',
    aperture: 'f/4.0',
    iso: '64',
    focalLength: '38mm',
    story: 'Waiting on the valley floor as the morning fog began to lift. The early rays hit the steep granite cliff of El Capitan in a perfect orange-gold glow.'
  },
  {
    id: '2',
    title: 'Brutalist Concrete Arches',
    category: 'Architecture',
    imageUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1600&auto=format&fit=crop&q=85',
    location: 'Geneva, Switzerland',
    date: 'Jun 21, 2025',
    camera: 'Leica M11',
    lens: 'Summilux-M 35mm f/1.4 ASPH',
    shutter: '1/1000s',
    aperture: 'f/8.0',
    iso: '100',
    focalLength: '35mm',
    story: 'An exploration of geometric shadows cast upon minimal concrete structures during the peak summer solstice sun.'
  },
  {
    id: '3',
    title: 'Neon Streets of Shinjuku',
    category: 'Street',
    imageUrl: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1600&auto=format&fit=crop&q=85',
    location: 'Tokyo, Japan',
    date: 'Nov 04, 2025',
    camera: 'Sony A7R V',
    lens: 'FE 50mm f/1.2 GM',
    shutter: '1/160s',
    aperture: 'f/1.6',
    iso: '800',
    focalLength: '50mm',
    story: 'Capturing the retro-futuristic rain reflection on Tokyo\'s tarmac under an expansive canopy of glowing neon and glowing umbrellas.'
  },
  {
    id: '4',
    title: 'The Golden Hours',
    category: 'Portrait',
    imageUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1600&auto=format&fit=crop&q=85',
    location: 'Paris, France',
    date: 'Aug 14, 2025',
    camera: 'Fujifilm GFX 100S',
    lens: 'GF 110mm f/2 R LM WR',
    shutter: '1/200s',
    aperture: 'f/2.2',
    iso: '100',
    focalLength: '110mm',
    story: 'Carefully modified studio lighting mimicking the warm late- afternoon sunbeams, emphasizing natural textures, micro-level details and soft depth.'
  },
  {
    id: '5',
    title: 'Nordic Coastal Sentinel',
    category: 'Landscape',
    imageUrl: 'https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=1600&auto=format&fit=crop&q=85',
    location: 'Lofoten Islands, Norway',
    date: 'Jan 18, 2026',
    camera: 'Hasselblad X2D 100C',
    lens: 'XCD 21mm f/4',
    shutter: '1/8s',
    aperture: 'f/11',
    iso: '64',
    focalLength: '21mm',
    story: 'A solitary structure standing the ground against wild subarctic winds and misty mountains just before the freezing twilight set in.'
  },
  {
    id: '6',
    title: 'Metropolitan Ribbons',
    category: 'Architecture',
    imageUrl: 'https://images.unsplash.com/photo-1518005020951-eccb494ad742?w=1600&auto=format&fit=crop&q=85',
    location: 'London, UK',
    date: 'Sep 03, 2025',
    camera: 'Leica M11',
    lens: 'Apo-Summicron-M 50mm f/2 ASPH',
    shutter: '1/500s',
    aperture: 'f/5.6',
    iso: '200',
    focalLength: '50mm',
    story: 'Ascending lines of steel and curved panels. This frame isolates the dark blue sky reflections slicing through contemporary glass architecture.'
  },
  {
    id: '7',
    title: 'Rain on the Yellow Cab',
    category: 'Street',
    imageUrl: 'https://images.unsplash.com/photo-1514924013411-cbf25faa35bb?w=1600&auto=format&fit=crop&q=85',
    location: 'New York City, USA',
    date: 'Oct 29, 2025',
    camera: 'Sony A7R V',
    lens: 'FE 85mm f/1.4 GM',
    shutter: '1/320s',
    aperture: 'f/1.4',
    iso: '400',
    focalLength: '85mm',
    story: 'Water streaks falling upon glass. This shot targets the motion blur of Manhattan rain combined with the signature stark yellow profile of an iconic cab.'
  },
  {
    id: '8',
    title: 'Monochrome Contemplation',
    category: 'Portrait',
    imageUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=1600&auto=format&fit=crop&q=85',
    location: 'Milan, Italy',
    date: 'Feb 12, 2026',
    camera: 'Leica M11 M (Monochrom)',
    lens: 'Summilux-M 75mm f/1.4',
    shutter: '1/125s',
    aperture: 'f/1.8',
    iso: '320',
    focalLength: '75mm',
    story: 'A high-contrast black and white studio portrait focusing purely on shadow patterns, lines of character, and raw analogue-like silver halic grain.'
  },
  {
    id: '9',
    title: 'Hot Air Balloons over Goreme',
    category: 'Landscape',
    imageUrl: 'https://images.unsplash.com/photo-1433832597046-4f10e10ac764?w=1600&auto=format&fit=crop&q=85',
    location: 'Cappadocia, Turkey',
    date: 'Jul 08, 2025',
    camera: 'Sony A7R V',
    lens: 'FE 24-70mm f/2.8 GM II',
    shutter: '1/800s',
    aperture: 'f/4.0',
    iso: '100',
    focalLength: '45mm',
    story: 'Witnessing the majestic morning flight from the highest cliffs of Uchisar, capturing deep natural terrain textures and tiny dots of hot-air balloons.'
  },
  {
    id: '10',
    title: 'Brutalist Concrete Minimal',
    category: 'Architecture',
    imageUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&auto=format&fit=crop&q=85',
    location: 'Berlin, Germany',
    date: 'Mar 15, 2026',
    camera: 'Fujifilm GFX 100S',
    lens: 'GF 32-64mm f/4 R LM WR',
    shutter: '1/125s',
    aperture: 'f/8.0',
    iso: '100',
    focalLength: '32mm',
    story: 'A structural photograph exploring geometric harmony and modern brutalist lines at the intersection of shadows and empty spaces.'
  },
  {
    id: '11',
    title: 'Kyoto Alleyway Study',
    category: 'Street',
    imageUrl: 'https://images.unsplash.com/photo-1504150559779-051f41eff35e?w=1600&auto=format&fit=crop&q=85',
    location: 'Kyoto, Japan',
    date: 'Nov 09, 2025',
    camera: 'Fujifilm X-T5',
    lens: 'XF 35mm f/1.4 R',
    shutter: '1/250s',
    aperture: 'f/2.0',
    iso: '200',
    focalLength: '35mm',
    story: 'A candid slice-of-life capture in the Gion district. A quiet alley bathed in shifting lights, framing the wooden slats and glowing lanterns.'
  },
  {
    id: '12',
    title: 'Natural Sunkissed Rimlight',
    category: 'Portrait',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=1600&auto=format&fit=crop&q=85',
    location: 'Provence, France',
    date: 'Jul 22, 2025',
    camera: 'Leica M11',
    lens: 'Summilux-M 50mm f/1.4 ASPH',
    shutter: '1/1000s',
    aperture: 'f/1.4',
    iso: '64',
    focalLength: '50mm',
    story: 'Shot in a lavender field during sunset. The heavy backlighting acts as a natural glowing rim that highlights fine strands of hair and warm skin tones.'
  }
];
